### ISSUE TITLE
App crashes when you try switching to another default gateway client

### ISSUE THREAD

**Issue by Idadelveloper** [smswithoutborders/SMSWithoutBorders-App-Android#133]
In case you visit the screen with  the list of available gateway client, click on the recents tab at the bottom navigation bar and go back to the gateway clients screen, upon trying to switch to another gateway client crashes the app

**Comment by sherlockwisdom** [comment]
https://github.com/smswithoutborders/SMSWithoutBorders-App-Android/commit/1e7d1e286b47e8fdc2ce68a79b224de8778fb424
